version: '3.9'
services:
  postgres_test:
    image: postgres:13
    container_name: vc_postgres_test
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vai_coxinha_test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
volumes:
  postgres_test_data:
